eureka: 
  client:
    serviceUrl: 
      defaultZone: http://192.168.10.118:8761/eureka/eureka/  
       

server:
  port: 8083
  enable-self-preservation: false #是否要设置成保护模式
  eviction-interval-timer-in-ms: 60000  #不通过eureka获取
spring: 
 application: 
   name: scrm-member
# datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.10.119:3306/ts_scrm?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#    username: ts_imcc
#    password: ts_imcc
#开启微服务
feign:
  hystrix:
    enabled: true

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
 #url: jdbc:mysql://localhost:3306/ts_imcc?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
 #username: root
 #password: root
  url: jdbc:mysql://192.168.10.119:3306/ts_scrm?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
  username: ts_imcc
  password: ts_imcc

#mybatis config
mybatis:
   typeAliasesPackage: cn.com.scrm.dto
   mapperLocations: classpath:mappers/*.xml
   configLocation: classpath:Mybatis-config.xml
   check-config-location: true   #检查mybatis的配置信息
   #configuration:
   #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
 

 